### ISSUE TITLE
CMakeList.txt currently requires a long list of files, we should have something that automatically adds those for us.

### ISSUE THREAD

**Issue by OdellDotson** [arthurlockman/wyatt#11]
Currently the way things are set up, the CMakeList.txt file at wyatt/src/ needs a list of every file we need to link for our compilation. Is there a better way than manually adding files to that list as the project grows? If there's nothing built in, we should build a tool that does that because it's a pain in the ass to modify that file every time we add a new file.

**Comment by arthurlockman** [comment]
There may be a way to use a wildcard, I will investigate.

**Comment by arthurlockman** [comment]
4af5cbcb942368b41d5dff6fea25db227998f626 starts fixing some of this.
