### ISSUE TITLE
ISensorManager: Communicator currently doesn't have a plan for what to do with data it reads

### ISSUE THREAD

**Issue by OdellDotson** [arthurlockman/wyatt#18]
I'm not sure if we designed this concretely and I forgot, or if we had loose ideas but no final plan.

Either way, currently I'm not sure what exactly we're doing with data that gets read in from arduinos. Do we just call some function from the ISensorManager? Maybe we should flesh out an implementation for a SensorManager so we know what we want to be doing with that data as it is read in. (Call a function from SensorManager to consume the data? Queue it and let a sensor manager thread call for the data when it wants it? Call for most recent data vs  oldest data in queue?)

**Comment by TuckerHaydon** [comment]
The data read in from the CommunicationManager should be delegated to an implementation of the ISensorManager interface. The ISensorManager interface needs to expose a function that will receive the data. What a SensorManager implementation does with the data is up to that implementation. From the perspective of the CommunicationManager however, all the communication manager has to do is give the data to the SensorManager.

ISensorManager should probably expose a function called handleData(data).
