### ISSUE TITLE
Arduino CLI deploy script broken

### ISSUE THREAD

**Issue by TuckerHaydon** [arthurlockman/wyatt#31]
- Raspi can't find the arduino command.
- While we do have arduino installed, the correct CLI is not installed.
- I imagine this is the CLI we want:
https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc

**Comment by arthurlockman** [comment]
Fixed in c7e5bd3ae375fcee2d2d8b3894de9d8599b10daf.
