### ISSUE TITLE
Encapsulate related source files in directories.

### ISSUE THREAD

**Issue by TuckerHaydon** [arthurlockman/wyatt#54]
The default directory is too full of files right now. They should be moved into subdirectories for related classes. Not sure what needs to change in CMake. This encapsulation should be mirrored in src/include.

1) Messages: IMessage, EncoderMessage, MotorMessage, etc
2) HardwareInterface: IHardwareInterface, EncoderCounter, Chassis
3) Exceptions: NonexistentHardwareException, DuplicateHardwareException, MessageLengthException, 
4) Commands: Command, CommandManager
5) Sensors: ISensor, IRangeFinderSensor, ISensorManager
etc.

**Comment by arthurlockman** [comment]
Fixed in 1ff2fa4b342e5eaa4ececd9f2c66ac5f1711910d
